name: Build
on: [push]
jobs:
  buildWindows: # e
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install hxcpp --quiet
    - name: Build project
      run: |
        haxelib run lime build windows