name: Build
on: 
  push:
jobs:
  buildWindows: # some stuff pulled from codename and psych because i fucking suck at this
    runs-on: windows-latest

    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v2
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      - name: Compile
        run: |
          haxelib run lime build windows
      - name: Uploading artifact 
        uses: actions/upload-artifact@v2
        with:
          name: windowsBuild
          path: export/release/windows/bin