name: Build
on: [push]
jobs:
  buildWindows: # e
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - name: Set up Haxelib dependencies # gotta find out how to make it launch batch file
      run: |
        call actionBuild.dat
    - name: Build project
      run: |
        haxelib run lime build windows
    - name: Uploading artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows Build
        path: export/release/windows/bin